#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/
pre-commit:
  parallel: true
  jobs:
    - name: markdown linting
      run: markdownlint-cli2 --fix --config .markdownlint-cli2.yaml {staged_files}
      glob:
        - "*.md"
      stage_fixed: true

    - name: shell script validation
      run: shellcheck --shell=bash -x {staged_files}
      glob:
        - "*.sh"
        - "*.zsh"
        - "*.bash"

    - name: GHA file linting
      run: actionlint {staged_files}
      glob:
        - ".github/workflows/*.yml"
        - ".github/workflows/*.yaml"

    - name: yaml file linting
      run: yamllint -c .yamllint-config.yaml {staged_files}
      glob:
        - "*.yml"
        - "*.yaml"

    - name: secret scan
      run: scripts/utils/secrets.sh

    - name: json validation
      run: scripts/utils/check-json.sh {staged_files}
      glob:
        - "*.json"

    - name: check for merge conflicts
      run: scripts/utils/check-merge-conflicts.sh {staged_files}

    - name: check for file details
      run: scripts/utils/check-file-details.sh {staged_files}
      stage_fixed: true
      env:
        - FILE_SIZE: 50000000

    - name: ruff check
      run: ruff check --fix {staged_files}
      glob:
        - "*.py"
      stage_fixed: true

    - name: ruff format
      run: ruff format {staged_files}
      glob:
        - "*.py"
      stage_fixed: true

    - name: python type checking
      run: scripts/utils/python-type-check.sh
      glob:
        - "*.py"

output:
  - success
  - failure
  - summary
