version: 2.1

defaults: &defaults
  machine:
    image: ubuntu-2404:2025.09.1

commands:
  env_vars:
    description: Add environment variables needed for steps
    steps:
      - run:
          name: configure environment
          command: |
            mkdir -p "${CIRCLE_WORKING_DIRECTORY}/.cache" "${CIRCLE_WORKING_DIRECTORY}/.bin/"
            echo "export MISE_QUIET=true" >> $BASH_ENV
            echo "export MISE_DATA_DIR=${CIRCLE_WORKING_DIRECTORY}/.cache/mise" >> $BASH_ENV
            echo "export MISE_INSTALL_PATH=${CIRCLE_WORKING_DIRECTORY}/.bin/mise" >> $BASH_ENV
            echo "export PATH=${CIRCLE_WORKING_DIRECTORY}/.bin/:$PATH" >> $BASH_ENV
            source $BASH_ENV
  setup_mise:
    description: Enable mise in our environment
    steps:
      - run:
          name: install/configure mise
          command: |
            source $BASH_ENV
            curl -SsLf https://mise.run | bash > /dev/null
            mise install python --quiet

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - env_vars
      - setup_mise
      - run:
          name: set up env
          command: |
            eval "$(mise activate bash)"
            pip install --upgrade pip wheel uv
            uv sync --frozen
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - env_vars
      - run:
          name: formatting
          command: |
            eval "$(mise activate bash)"
            uv run ruff format --diff
      - run:
          name: linting
          command: |
            eval "$(mise activate bash)"
            uv run ruff check
      - run:
          name: typing
          command: |
            eval "$(mise activate bash)"
            uv run mypy .

  pytests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - env_vars
      - run:
          name: tests
          command: |
            eval "$(mise activate bash)"
            uv run pytest


workflows:
  ci-cd:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - pytests:
          requires:
            - setup
